
[req]
distinguished_name = req_distinguished_name
req_extensions = v3_req
x509_extensions = v3_req
prompt = no

[req_distinguished_name]
CN = Federated-Node-Network
O = A3K
OU = GEC SKP 22-26 CSE

[v3_req]
subjectAltName = @alt_names

[alt_names]
DNS.1 = laptop-3hb2ene1
DNS.2 = fedora
DNS.3 = laptop-3hb2ene1.tailca8536.ts.net
DNS.4 = fedora.tail917d49.ts.net
DNS.5 = localhost
IP.1 = 100.94.68.3
IP.2 = 100.80.113.9
IP.3 = 100.80.113.8
IP.4 = 100.94.68.4
IP.5 = 127.0.0.1
